# Generated by Django 3.2.6 on 2021-10-14 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('juego', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='categoria_pregunta',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='juego.categoria'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='pregunta',
            field=models.TextField(max_length=200),
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.TextField(max_length=200)),
                ('valida', models.BooleanField(default=False)),
                ('pregunta_respuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='juego.pregunta')),
            ],
        ),
    ]
