# Generated by Django 3.2.6 on 2021-10-15 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('juego', '0003_nivel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='premio_categoria',
        ),
    ]
