# Generated by Django 3.2.6 on 2021-10-18 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('juego', '0007_jugador'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jugador',
            options={'ordering': ['-premio']},
        ),
    ]
